config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'about' ,to: 'welcome#about'
  get 'contact' ,to: 'welcome#contact'
  resources :users
  resources :products
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories ,expect: [:destroy]
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :product_categories
  has_many :categories, through: :product_categories
  validates :name ,presence: true,length: {minimum: 2,maxnimum:50}
  validates :decsription ,presence: true,length: {minimum: 2,maxnimum:50}
  validates :user_id,presence:true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :set_product,only: [:edit,:destroy,:update,:show]
before_action :require_user,expect: [:index,:show]
before_action :require_same_user,only: [:edit,:update,:destroy]

def index
 @products = Product.paginate(page:params[:page],per_page: 3)
end

def new
   @product = Product.new
end

def create
  # debugger

   @product = Product.new(product_params)
   @product.user = current_user  
   @product.dayinput = Time.now
   if @product.save
   	   flash[:success] = "Product was successfully with product name : " + @product.name #flash la mot mang hash (mang lien ket)
       redirect_to product_path (@product)
   else
   	render 'new'
   end
end

def destroy
	@product.destroy
	flash[:danger] = " Product was destroy successfully " 
	redirect_to products_path
end

def show

end

def edit

end 

def update
 if !Product.exists?(:name => product_params[:name]) then #kiem tra trung username
   if @user.update(product_params)
   	   flash[:success] = "Product was successfully" 
       redirect_to product_path (@product)
   else
   	render 'new'
   end
 else
   flash[:success] = "name product don't like" 
   redirect_to product_path (@product)
 end
end

	

 private
   def set_product
     @product = Product.find(params[:id])
   end

   def product_params
   	params.require(:product).permit(:name,:decsription, category_ids: [])
   end

   def require_same_user
    if current_user != @product.user && current_user.admin?
      flash[:danger] = "You can only edit or delete your owm product"
      redirect_to root_path
    end
   end


end

app/views/products/_form.html.erb
<%= form_for(@product , :html => {class: "form-horizontal", role: "form"}) do |f| %>
<div class="form-group">
	<%= f.label :name ,class: "col-sm-2 control-label"%>
	<div class="col-sm-10">
		<%= f.text_field :name, class: "form-control", placeholder: "Title of article", autofocus: true  %>
	</div>
</div>
<div class="form-group">
	<%= f.label :decsription,class: "col-sm-2 control-label" %>
	<div class="col-sm-10">
		<%= f.text_field :decsription, class: "form-control", placeholder: "Title of article", autofocus: true %>
	</div>
</div>
<div class="form-group">
	<div class="row">
		<div class="col-sm-offset-2 col-sm-8">
			<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
			<% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
			<% end %>
		</div>
	</div>
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<%= f.submit class: "btn btn-default" %>
	</div>
</div>
<div class="col-xs-4 col-xs-offset-4">
	[ <%= link_to "Cancel request and return to products listing", products_path %> ]
</div>
<% end %>

app/views/products/_product.html.erb
<%= link_to "Create product",new_product_path %>
<h1 align="center">Listing all Products</h1>
<% obj.each do |p| %>
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="well well-lg">
			<div class="user-title">
				<%= link_to p.name, products_path(p) %>
			</div>
			<div class="user-body">
				<%= truncate(p.decsription, length: 15) %>
				</small>
				Create for : <li>Created by:</li>
				<li><%= link_to gravatar_for(p.user), users_path(p.user) %></li>
				<li class="article-title">
					<%= link_to p.user.username, users_path(p.user) %>
				</li>
				<%= time_ago_in_words(p.dayinput) %>ago,
				last updated: <%= time_ago_in_words(p.updated_at)
				%> ago</small>
			</div>
			<% if p.categories.any? %>
			<p>Categories: <%= render p.categories %></p>
			<% end %>
			<% if logged_in? && (current_user == p.user || current_user.admin?) %>
			<div class="user-actions">
				<%= link_to "Edit this product", edit_product_path(p), class: "btn btn-xs btn-primary" %>
				<%= link_to "Delete this product", product_path(p), method: :delete,
				data: { confirm: "Are you sure you want to delete the product?"},
				class: "btn btn-xs btn-danger" %>
			</div>
			<% end %>
		</div>
	</div>
</div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit User Profile</h1>
<%= render 'form' %>

app/views/products/index.html.erb
<%= link_to "Create product",new_product_path %>
<h1 align="center">Listing all Products</h1>
<div align="center">
	<%= will_paginate %>
</div>
<%= render 'product',obj:@products %>
<div align="center">
	<%= will_paginate %>
</div>

app/views/products/new.html.erb
<h1> Create a product </h1>
<%= render 'form' %>

app/views/products/show.html.erb
<h1>Info</h1>
<h2 align="center"> <%= @product.name %></h2>
<h2 align="center">for acccount : <%= @product.user.username %></h2>
<div class="well col-xs-8 col-xs-offset-2">
	<h4 class="center email"><strong>Description</strong></h4>
	<hr>
	<%= simple_format(@product.decsription) %>
	create for : <li><%= link_to gravatar_for(@product.user), users_path(@product.user) %>
		<%= link_to @product.user.username, users_path(@product.user) %>
	</li>
	<% if @product.categories.any? %>
	<p>Categories: <%= render @product.categories %></p>
	<% end %>
	<% if logged_in? && (current_user == @product.user || current_user.admin?) %>
	<div class="user-actions">
		<%= link_to "Edit this product", edit_product_path(@product), class: "btn btn-xs btn-primary" %>
		<%= link_to "Delete this product", products_path(@product), method: :delete,
		data: { confirm: "Are you sure you want to delete the user?"},
		class: "btn btn-xs btn-danger" %>
		<%= link_to "View all product", products_path, class: "btn btn-xs btn-success" %>
	</div>
	<% end %>
</div>