config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'about' ,to: 'welcome#about'
  get 'contact' ,to: 'welcome#contact'
  resources :users
  resources :products
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories ,expect: [:destroy]
end

app/views/layouts/_footer.html.erb
<div class="container-fluid">
	<footer class="footer">
		<small>
			Coppyright &copy; <a href="#">ARYSTORE</a>
			by <a href="#">quoctienphamm</a>
		</small>
		<nav>
			<ul style="list-style-type: none">
				<li>
				 <%= link_to "about",about_path  %>
				</li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_messages.html.erb
 <ul>
 	  <% flash.each do |name,msg| %>
      <li>
      
        <%= msg %>
      </li>
      <% end %>
    </ul>

app/views/layouts/_navigation.html.erb
Dropdown
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <!--  <a class="navbar-brand" href="#">Ary STORE</a> -->
      <%= link_to "Ary STORE" , root_path , class: "navbar-brand"%>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--         <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        -->        <li><%= link_to "User" , users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New user" ,new_user_path%></li>
            <li><%= link_to "New product" ,new_product_path%></li>
            <!--             <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li> -->
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Categories", categories_path %></li>
            <% Category.all.each do |category| %>
            <li><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>
            <% if logged_in? and current_user.admin? %>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Create New Category", new_category_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= session[:user_id] == nil ? "Account": current_user.admin==true ? "Admin" : current_user.username   %>
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% if logged_in? %>
              <li><%= link_to "Edit profile",edit_user_path(current_user) %></li>
              <li><%= link_to "View your profile",user_path(current_user) %></li>
              <li><%= link_to "log out",logout_path,method: :delete %></li>
              <% else %>
              <li><%= link_to "log in",login_path  %></li>
              
              <% end %>
              
            </ul>
          </li>
        </ul>
        </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation'%>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>